name: Deploy on dev branch update

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Permet de d√©clencher le workflow manuellement
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files with rsync
      run: |
        rsync -avz --exclude='storage/' --exclude='.git' --exclude='.gitignore' --exclude='.github/' -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}

    - name: Run Composer commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.SSH_PATH }}
          composer install
          composer update
          composer dump-autoload
        EOF
