name: Deploy on dev branch update

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Permet de déclencher le workflow manuellement
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Installer les dépendances Composer
        run: composer install -n --prefer-dist
      - name: Lancer les tests PHPUnit
        run: php bin/phpunit
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files with rsync
      run: |
        rsync -rlvz --delete --exclude-from='.gitignore' --exclude='.env' --exclude='vendor/' --exclude='.github/' --exclude='/public/images/accueil/' --exclude='Dockerfile' --exclude='docker-compose.yml' -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
    - name: Run Composer commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.SSH_PATH }}
          composer install
          composer update
          composer dump-autoload
        EOF

